### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by aspnetcs** [iamchucky/speech2text-anywhere#1]
There is a virus in speech2text-anywhere,which is detected by 360 antivirus software.

**Comment by iamchucky** [comment]
not sure why 360 antivirus thinks this is a virus, can you please provide more information or a screenshot?

in any case, this project was meant for my personal use, so feel free to disregard this project

**Comment by aspnetcs** [comment]
sorry ，this is no virus。how to extract text from mp3,wav etc .on

**Comment by aspnetcs** [comment]
sorry,it is  a mistake.
how to convert audio files(wav,mp3,etc.on) to  text? 



--


At 2019-02-15 17:16:11, "Chuck Yang" <notifications@github.com> wrote:


not sure why 360 antivirus thinks this is a virus, can you please provide more information or a screenshot?

in any case, this project was meant for my personal use, so feel free to disregard this project
